package com.demat.invoice.aws.lambda;

public class DownloadUrlInput {

  private String cloudfront_url;
  // validity time in second from now of the signed url generated by the lambda
  private Long expires;

  public String getCloudfront_url() {
    return cloudfront_url;
  }

  public void setCloudfront_url(String cloudfront_url) {
    this.cloudfront_url = cloudfront_url;
  }

  public Long getExpires() {
    return expires;
  }

  public void setExpires(Long expires) {
    this.expires = expires;
  }

}
